import xml.etree.ElementTree as ET


def register_namespaces():
    ET.register_namespace("cmdty", "http://www.gnucash.org/XML/cmdty")
    ET.register_namespace("price", "http://www.gnucash.org/XML/price")
    ET.register_namespace("ts", "http://www.gnucash.org/XML/ts")
    ET.register_namespace("gnc", "http://www.gnucash.org/XML/gnc")
    ET.register_namespace("act", "http://www.gnucash.org/XML/act")
    ET.register_namespace("book", "http://www.gnucash.org/XML/book")
    ET.register_namespace("cd", "http://www.gnucash.org/XML/cd")
    ET.register_namespace("cmdty", "http://www.gnucash.org/XML/cmdty")
    ET.register_namespace("price", "http://www.gnucash.org/XML/price")
    ET.register_namespace("slot", "http://www.gnucash.org/XML/slot")
    ET.register_namespace("split", "http://www.gnucash.org/XML/split")
    ET.register_namespace("sx", "http://www.gnucash.org/XML/sx")
    ET.register_namespace("trn", "http://www.gnucash.org/XML/trn")
    ET.register_namespace("ts", "http://www.gnucash.org/XML/ts")
    ET.register_namespace("fs", "http://www.gnucash.org/XML/fs")
    ET.register_namespace("bgt", "http://www.gnucash.org/XML/bgt")
    ET.register_namespace("recurrence", "http://www.gnucash.org/XML/recurrence")
    ET.register_namespace("lot", "http://www.gnucash.org/XML/lot")
    ET.register_namespace("addr", "http://www.gnucash.org/XML/addr")
    ET.register_namespace("billterm", "http://www.gnucash.org/XML/billterm")
    ET.register_namespace("bt-days", "http://www.gnucash.org/XML/bt-days")
    ET.register_namespace("bt-prox", "http://www.gnucash.org/XML/bt-prox")
    ET.register_namespace("cust", "http://www.gnucash.org/XML/cust")
    ET.register_namespace("employee", "http://www.gnucash.org/XML/employee")
    ET.register_namespace("entry", "http://www.gnucash.org/XML/entry")
    ET.register_namespace("invoice", "http://www.gnucash.org/XML/invoice")
    ET.register_namespace("job", "http://www.gnucash.org/XML/job")
    ET.register_namespace("order", "http://www.gnucash.org/XML/order")
    ET.register_namespace("owner", "http://www.gnucash.org/XML/owner")
    ET.register_namespace("taxtable", "http://www.gnucash.org/XML/taxtable")
    ET.register_namespace("tte", "http://www.gnucash.org/XML/tte")
    ET.register_namespace("vendor", "http://www.gnucash.org/XML/vendor")
